sudo: required

language: cpp

services:
  - docker

script:
  - sudo docker build -t --build-arg coveralls_token=$COVERALLS_TOKEN --build-arg travis_build=true fiuba-taller2-tallerify-app-server .

notifications:
    email: false
