sudo: required

language: cpp

services:
  - docker

before_script:
  - sudo docker build --build-arg coveralls_token=$COVERALLS_TOKEN --build-arg travis_service=travis-ci -t tallerify .

script:
  - sudo docker run -t -i tallerify /bin/bash -c "./fiuba_taller2_tallerify_app_server"
  - sudo docker run -t -i tallerify /bin/bash -c "python ../tests/functional/api_tests.py"

after_success:
  - sudo docker run -t -i tallerify /bin/bash -c "make coveralls"

notifications:
    email: false
