sudo: required

language: cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -VV

after_success:
    - make test
    - coveralls --exclude lib --exclude test --gcov-options '\-lp'

notifications:
    email: false

