sudo: required

language: cpp

compiler:
  - gcc

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh --no-check-certificate
  - chmod +x cmake-3.6.3-Linux-x86_64.sh
  - ./cmake-3.6.3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
  - pip install --user cpp-coveralls

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - ./configure --enable-gcov && make && make check

after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
    email: false

