sudo: required

language: cpp

services:
  - docker

before_script:
  - sudo docker build --build-arg COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN --build-arg travis_build=$CI -t tallerify .

script:
  - sudo docker run -t -i tallerify

notifications:
    email: false
