language: cpp

compiler:
  - gcc

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh
  - chmod +x cmake-3.6.3-Linux-x86_64.sh
  - ./cmake-3.6.3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
