sudo: required

language: cpp

compiler:
  - gcc

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh --no-check-certificate
  - chmod +x cmake-3.6.3-Linux-x86_64.sh
  - ./cmake-3.6.3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
  - wget https://github.com/google/googletest/archive/release-1.7.0.zip --no-check-certificate && unzip release-1.7.0.zip
  - cd googletest-release-1.7.0 && ls && mkdir mybuild && cd mybuild  && cmake -DBUILD_SHARED_LIBS=ON -Dgtest_build_samples=ON -G"Unix Makefiles" .. && make && cp -r ../include/gtest/ /usr/local/include/ && cp lib*.so /usr/local/lib/
  - sudo bash -c 'echo /usr/local/lib >> /etc/ld.so.conf ' && sudo ldconfig

before_script:
    - mkdir build
    - cd build
    - cmake -Dtest=ON ..

script:
    - make
    - make test

notifications:
    email: false

