sudo: required

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install -y lcov
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh --no-check-certificate
  - chmod +x cmake-3.6.3-Linux-x86_64.sh
  - ./cmake-3.6.3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake -Dtest=ON ..
  - make

after_success:
    - make test
    - coveralls --exclude lib --exclude test --gcov-options '\-lp'

notifications:
    email: false

