

#ifndef FIUBA_TALLER2_TALLERIFY_APP_SERVER_CONSTANTS_H
#define FIUBA_TALLER2_TALLERIFY_APP_SERVER_CONSTANTS_H

/**
 * @file Constants.h
 */
#define HTTP_GET "GET"
#define HTTP_POST "POST"
#define HTTP_PUT "PUT"
#define HTTP_DELETE "DELETE"
#define HTTP_OK 200
#define HTTP_CREATED 201
#define HTTP_BAD_REQUEST 400
#define HTTP_NOT_FOUND 404
#define HTTP_FORBIDDEN 403
#define HTTP_SERVER_ERROR 500
#define BASE_URL "http://127.0.0.1:8080"

#endif //FIUBA_TALLER2_TALLERIFY_APP_SERVER_CONSTANTS_H
